#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo "You have to specify one python file to submit"
elif [ "$#" -gt 1 ]; then
    echo "You can only specify one python file at a time"
fi

target_file=$1

screen -dm bash -c "spark-submit --packages com.databricks:spark-csv_2.10:1.5.0 $target_file 2> logs/spark_verbose.log 1> logs/script_output.log"